name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: Install
        run: yarn install --immutable

      - name: Build
        env:
          VITE_AUTHORIZATION_TOKEN: ${{ vars.VITE_AUTHORIZATION_TOKEN }}
          VITE_GRAPHQL_URL: ${{ vars.VITE_GRAPHQL_URL }}
        run: |
          echo "Public auth token: $VITE_AUTHORIZATION_TOKEN"
          echo "GraphQL URL: $VITE_GRAPHQL_URL"
          yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
